language: node_js
node_js:
  - "stable"
script:
  - npm run test:coveralls
notifications:
  email: false

# below was not working well
# language: node_js
# node_js:
#   - stable
# jobs:
#   include:
#     # Define the release stage that runs semantic-release
#     - stage: release
#       node_js: stable
#       # Advanced: optionally overwrite your default `script` step to skip the tests
#       # script: skip
#       deploy:
#         provider: script
#         skip_cleanup: true
#         script:
#           - npm run semantic-release